---
title: "COVID-19 dashboard de Zdendulak"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(DT)

LIMIT_CASE <- 100
LIMIT_DEATH <- 10

LIMIT_CASE_RATE <- 1
LIMIT_DEATH_RATE <- 0.1

# https://data.worldbank.org/indicator/SP.POP.TOTL
pop_raw <- read_csv("../analysis/API_SP.POP.TOTL_DS2_en_csv_v2_887275.csv", 
                    skip = 4) %>% 
  select(`Country Name`, `2018`) %>% 
  rename(country = `Country Name`,
         population = `2018`)

time_series_covid19_confirmed_global <- 
  read_csv(paste0("../csse_covid_19_data/csse_covid_19_time_series/",
                  "time_series_covid19_confirmed_global.csv"))

time_series_covid19_deaths_global <- 
  read_csv(paste0("../csse_covid_19_data/csse_covid_19_time_series/",
                  "time_series_covid19_deaths_global.csv"))

cases <- time_series_covid19_confirmed_global %>% 
  select(-`Province/State`, -Lat, -Long) %>% 
  pivot_longer(-`Country/Region`, 
               names_to = "date", values_to = "cases_cum") %>% 
  rename(country = `Country/Region`) %>% 
  mutate(date = mdy(date)) %>% 
  group_by(country, date) %>% 
  summarize(cases_cum = sum(cases_cum)) %>% 
  mutate(cases_new = cases_cum - lag(cases_cum),
         cases_growth_rate_pct = round(cases_new/lag(cases_cum)*100, 1)) %>% 
  ungroup()

deaths <- time_series_covid19_deaths_global %>% 
  select(-`Province/State`, -Lat, -Long) %>% 
  pivot_longer(-`Country/Region`, 
               names_to = "date", values_to = "deaths_cum") %>% 
  rename(country = `Country/Region`) %>% 
  mutate(date = mdy(date)) %>% 
  group_by(country, date) %>% 
  summarize(deaths_cum = sum(deaths_cum)) %>% 
  mutate(deaths_new = deaths_cum - lag(deaths_cum),
         deaths_growth_rate_pct = round(deaths_new/lag(deaths_cum)*100, 1)) %>% 
  ungroup()

data <- full_join(cases, deaths)

data <- data %>%
  group_by(country) %>% 
  mutate(case_ind = ifelse(cases_cum >= LIMIT_CASE, 1, 0),
         days_since_limit_case = cumsum(case_ind),
         death_ind = ifelse(deaths_cum >= LIMIT_DEATH, 1, 0),
         days_since_limit_death = cumsum(death_ind)) %>% 
  ungroup() %>% 
  select(-case_ind, -death_ind)

mapping <- tibble(
  country = 
    c("Bahamas, The", "Brunei Darussalam", "Myanmar", "Congo, Rep.", 
      "Congo, Dem. Rep.", "Czech Republic", "Diamond Princess", 
      "Egypt, Arab Rep.", "Gambia, The", "Holy See", "Iran, Islamic Rep.", 
      "Korea, Rep.", "Kyrgyz Republic", "Lao PDR", "MS Zaandam", 
      "Russian Federation", "St. Kitts and Nevis", "St. Lucia" , 
      "St. Vincent and the Grenadines", "Slovak Republic", 
      "Syrian Arab Republic", "Taiwan*", "United States", "Venezuela, RB"),
  country_covid = as.character(setdiff(data$country, pop_raw$country))
)

pop <- full_join(pop_raw, mapping) %>% 
  mutate(country = ifelse(is.na(country_covid), country, country_covid)) %>% 
  select(country, population)

pop$population[pop$country == "Diamond Princess"] <- 3711
pop$population[pop$country == "MS Zaandam"] <- 1829
pop$population[pop$country == "Holy See"] <- 800
pop$population[pop$country == "Taiwan*"] <- 23780452

data <- left_join(data, pop)

data <- data %>% 
  mutate(cases_cum_per_100k = round(cases_cum/population*100000, 3),
         cases_new_per_100k = round(cases_new/population*100000, 3),
         deaths_cum_per_100k = round(deaths_cum/population*100000, 6),
         deaths_new_per_100k = round(deaths_new/population*100000, 6))

data <- data %>% 
  group_by(country) %>% 
  mutate(case_rate_ind = ifelse(cases_cum_per_100k >= LIMIT_CASE_RATE, 1, 0),
         days_since_limit_case_rate = cumsum(case_rate_ind),
         death_rate_ind = ifelse(deaths_cum_per_100k >= LIMIT_DEATH_RATE, 1, 0),
         days_since_limit_death_rate = cumsum(death_rate_ind)) %>% 
  ungroup() %>% 
  select(-case_rate_ind, -death_rate_ind)

latest_date <- max(cases$date)
```

Global overview
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Global cases and deaths

```{r}
data %>%
  select(date, cases_cum, cases_new, deaths_cum, deaths_new) %>% 
  group_by(date) %>% 
  summarize_all(.funs = sum, na.rm = TRUE) %>% 
  arrange(desc(date)) %>% 
  datatable()
```

Column {data-width=500}
-----------------------------------------------------------------------

### Global new cases

```{r}
g <- data %>%
  select(date, cases_cum, cases_new, deaths_cum, deaths_new) %>% 
  group_by(date) %>% 
  summarize_all(.funs = sum, na.rm = TRUE) %>% 
  filter(date >= dmy("01-03-2020")) %>% 
  ggplot(aes(x = date, y = cases_new)) + 
  geom_point(color = "navy") + geom_smooth()

ggplotly(g)
```

### Global new deaths

```{r}
g <- data %>%
  select(date, cases_cum, cases_new, deaths_cum, deaths_new) %>% 
  group_by(date) %>% 
  summarize_all(.funs = sum, na.rm = TRUE) %>% 
  filter(date >= dmy("01-03-2020")) %>% 
  ggplot(aes(x = date, y = deaths_new)) + 
  geom_point(color = "navy") + geom_smooth()

ggplotly(g)
```

Case overview
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Cases last day

```{r}
data %>% 
  filter(date == latest_date) %>% 
  select(country, cases_cum, cases_new, 
         cases_cum_per_100k, cases_new_per_100k) %>% 
  arrange(desc(cases_cum)) %>% 
  datatable(colnames = c("Country", "Total cases", "New cases",
                         "Total cases per 100k", "New cases per 100k"),
            rownames = FALSE,
            options = list(pageLength = 15))
```


Column {data-width=500}
-----------------------------------------------------------------------

### Total cases per country


```{r}
g <- data %>% 
  filter(date == latest_date) %>% 
  top_n(20, cases_cum) %>% 
  ggplot(aes(y = reorder(country, cases_cum), x = cases_cum)) + 
  geom_bar(stat = "identity")

ggplotly(g)
```

### Total case rate per country

```{r}
g <- data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, cases_cum_per_100k) %>% 
  ggplot(aes(y = reorder(country, cases_cum_per_100k), x = cases_cum_per_100k))+ 
  geom_bar(stat = "identity")

ggplotly(g)
```


Column {data-width=500}
-----------------------------------------------------------------------

### Total new cases per country

```{r}
g <- data %>% 
  filter(date == latest_date) %>% 
  top_n(20, cases_new) %>% 
  ggplot(aes(y = reorder(country, cases_new), x = cases_new)) + 
  geom_bar(stat = "identity")

ggplotly(g)
```


### Total new case rate per country

```{r}
g <- data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, cases_new_per_100k) %>% 
  ggplot(aes(y = reorder(country, cases_new_per_100k), x = cases_new_per_100k))+ 
  geom_bar(stat = "identity")

ggplotly(g)
```



