---
title: "COVID-19 notebook"
output: html_notebook
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)

# https://data.worldbank.org/indicator/SP.POP.TOTL
pop_raw <- read_csv("../analysis/API_SP.POP.TOTL_DS2_en_csv_v2_887275.csv", skip = 4) %>% 
  select(`Country Name`, `2018`) %>% 
  rename(country = `Country Name`,
         population = `2018`)

time_series_covid19_confirmed_global <- read_csv("../csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")

time_series_covid19_deaths_global <- read_csv("../csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
```

```{r}
cases <- time_series_covid19_confirmed_global %>% 
  select(-`Province/State`, -Lat, -Long) %>% 
  pivot_longer(-`Country/Region`, names_to = "date", values_to = "cases_cum") %>% 
  rename(country = `Country/Region`) %>% 
  mutate(date = mdy(date)) %>% 
  group_by(country, date) %>% 
  summarize(cases_cum = sum(cases_cum)) %>% 
  mutate(cases_new = cases_cum - lag(cases_cum),
         cases_growth_rate_pct = round(cases_new/lag(cases_cum)*100, 1)) %>% 
  ungroup()

deaths <- time_series_covid19_deaths_global %>% 
  select(-`Province/State`, -Lat, -Long) %>% 
  pivot_longer(-`Country/Region`, names_to = "date", values_to = "deaths_cum") %>% 
  rename(country = `Country/Region`) %>% 
  mutate(date = mdy(date)) %>% 
  group_by(country, date) %>% 
  summarize(deaths_cum = sum(deaths_cum)) %>% 
  mutate(deaths_new = deaths_cum - lag(deaths_cum),
         deaths_growth_rate_pct = round(deaths_new/lag(deaths_cum)*100, 1)) %>% 
  ungroup()

data <- full_join(cases, deaths)

data <- data %>%
  group_by(country) %>% 
  mutate(over_100_ind = ifelse(cases_cum >= 100, 1, 0),
         days_since_case_100 = cumsum(over_100_ind),
         over_10d_ind = ifelse(deaths_cum >= 10, 1, 0),
         days_since_death_10 = cumsum(over_10d_ind)) %>% 
  ungroup() %>% 
  select(-over_100_ind, -over_10d_ind)

mapping <- tibble(
  country = c("Bahamas, The", "Brunei Darussalam", "Myanmar", "Congo, Rep.", "Congo, Dem. Rep.", 
              "Czech Republic", "Diamond Princess", "Egypt, Arab Rep.", "Gambia, The", 
              "Holy See", "Iran, Islamic Rep.", "Korea, Rep.", "Kyrgyz Republic", "Lao PDR", "MS Zaandam",
              "Russian Federation", "St. Kitts and Nevis", "St. Lucia" , 
              "St. Vincent and the Grenadines", "Slovak Republic", "Syrian Arab Republic", 
              "Taiwan*", "United States", "Venezuela, RB"),
  country_covid = as.character(setdiff(data$country, pop_raw$country))
)

pop <- full_join(pop_raw, mapping) %>% 
  mutate(country = ifelse(is.na(country_covid), country, country_covid)) %>% 
  select(country, population)

pop$population[pop$country == "Diamond Princess"] <- 3711
pop$population[pop$country == "MS Zaandam"] <- 1829
pop$population[pop$country == "Holy See"] <- 800
pop$population[pop$country == "Taiwan*"] <- 23780452

data <- left_join(data, pop)

data <- data %>% 
  mutate(cases_cum_per_100k = round(cases_cum/population*100000, 3),
         cases_new_per_100k = round(cases_new/population*100000, 3),
         deaths_cum_per_100k = round(deaths_cum/population*100000, 6),
         deaths_new_per_100k = round(deaths_new/population*100000, 6))

data <- data %>% 
  group_by(country) %>% 
  mutate(over_1per100k_ind = ifelse(cases_cum_per_100k >= 1, 1, 0),
         days_since_1per100k = cumsum(over_1per100k_ind),
         over_1dperm_ind = ifelse(deaths_cum_per_100k >= 0.1, 1, 0),
         days_since_1d_per_m = cumsum(over_1dperm_ind)) %>% 
  ungroup() %>% 
  select(-over_1per100k_ind, -over_1dperm_ind)

# write.csv(data, "../analysis/merged.csv")
```
```{r}
data %>%
  select(date, cases_cum, cases_new, deaths_cum, deaths_new) %>% 
  group_by(date) %>% 
  summarize_all(.funs = sum, na.rm = TRUE) %>% 
  arrange(desc(date))

data %>%
  select(date, cases_cum, cases_new, deaths_cum, deaths_new) %>% 
  group_by(date) %>% 
  summarize_all(.funs = sum, na.rm = TRUE) %>% 
  filter(date >= dmy("01-03-2020")) %>% 
  ggplot(aes(x = date, y = cases_new)) + geom_point(color = "navy") + geom_smooth()
```



```{r}
latest_date <- max(cases$date)

data %>% 
  filter(date == latest_date) %>% 
  select(-date) %>% 
  arrange(desc(cases_new))

data %>% 
  group_by(date) %>% 
  summarize(cases_total = sum(cases_cum),
            cases_new = sum(cases_new),
            deaths_total = sum(deaths_cum),
            deaths_new = sum(deaths_new)) %>% 
  filter(date >= dmy("01-03-2020")) %>% 
  ggplot(aes(x = date, y = cases_new)) + geom_bar(stat = "identity")

data %>% 
  filter(date == latest_date) %>% 
  top_n(20, cases_cum) %>% 
  ggplot(aes(y = reorder(country, cases_cum), x = cases_cum)) + geom_bar(stat = "identity")

data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, cases_cum_per_100k) %>% 
  ggplot(aes(y = reorder(country, cases_cum_per_100k), x = cases_cum_per_100k)) + geom_bar(stat = "identity")


data %>% 
  filter(date == latest_date) %>% 
  top_n(20, cases_new) %>% 
  ggplot(aes(y = reorder(country, cases_new), x = cases_new)) + geom_bar(stat = "identity")

data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, cases_new_per_100k) %>% 
  ggplot(aes(y = reorder(country, cases_new_per_100k), x = cases_new_per_100k)) + geom_bar(stat = "identity")
```

```{r}
data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  arrange(desc(cases_growth_rate_pct))

data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, cases_growth_rate_pct) %>% 
  ggplot(aes(y = reorder(country, cases_growth_rate_pct), x = cases_growth_rate_pct)) + 
  geom_bar(stat = "identity")

data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, deaths_growth_rate_pct) %>% 
  ggplot(aes(y = reorder(country, deaths_growth_rate_pct), x = deaths_growth_rate_pct)) + 
  geom_bar(stat = "identity")
```

```{r}
data %>% 
  filter(date == latest_date) %>% 
  top_n(20, deaths_cum) %>% 
  ggplot(aes(y = reorder(country, deaths_cum), x = deaths_cum)) + geom_bar(stat = "identity")

data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, deaths_cum_per_100k) %>% 
  ggplot(aes(y = reorder(country, deaths_cum_per_100k), x = deaths_cum_per_100k)) + geom_bar(stat = "identity")


data %>% 
  filter(date == latest_date) %>% 
  top_n(20, deaths_new) %>% 
  ggplot(aes(y = reorder(country, deaths_new), x = deaths_new)) + geom_bar(stat = "identity")

data %>% 
  filter(date == latest_date,
         cases_cum >= 1000) %>% 
  top_n(20, cases_new_per_100k) %>% 
  ggplot(aes(y = reorder(country, deaths_new_per_100k), x = deaths_new_per_100k)) + geom_bar(stat = "identity")
```


```{r}
top_countries <- function(n) {
  data %>% 
  filter(date == latest_date) %>% 
  top_n(n, cases_new) %>% 
  pull(country)
}

cutoff_days <- 40

data %>% 
  filter(country %in% top_countries(10),
         days_since_case_100 != 0,
         days_since_case_100 < cutoff_days) %>% 
  ggplot(aes(x = days_since_case_100, y = cases_cum, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')

data %>% 
  filter(country %in% setdiff(top_countries(20), top_countries(10)),
         days_since_case_100 != 0,
         days_since_case_100 < cutoff_days) %>% 
  ggplot(aes(x = days_since_case_100, y = cases_cum, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')

data %>% 
  filter(country %in% top_countries(10),
         days_since_1per100k != 0,
         days_since_1per100k < cutoff_days) %>% 
  ggplot(aes(x = days_since_1per100k, y = cases_cum_per_100k, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')

data %>% 
  filter(country %in% setdiff(top_countries(20), top_countries(10)),
         days_since_1per100k != 0,
         days_since_1per100k < cutoff_days) %>% 
  ggplot(aes(x = days_since_1per100k, y = cases_cum_per_100k, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')
```

```{r}
data %>% 
  filter(country %in% top_countries(10),
         days_since_death_10 != 0,
         days_since_death_10 < cutoff_days) %>% 
  ggplot(aes(x = days_since_death_10, y = deaths_cum, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')

data %>% 
  filter(country %in% setdiff(top_countries(20), top_countries(10)),
         days_since_death_10 != 0,
         days_since_death_10 < cutoff_days) %>% 
  ggplot(aes(x = days_since_death_10, y = deaths_cum, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')

data %>% 
  filter(country %in% top_countries(10),
         days_since_1d_per_m != 0,
         days_since_1d_per_m < cutoff_days) %>% 
  ggplot(aes(x = days_since_1d_per_m, y = deaths_cum_per_100k, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')

data %>% 
  filter(country %in% setdiff(top_countries(20), top_countries(10)),
         days_since_1d_per_m != 0,
         days_since_1d_per_m < cutoff_days) %>% 
  ggplot(aes(x = days_since_1d_per_m, y = deaths_cum_per_100k, color = country)) + 
  geom_line() + geom_point() +
  scale_y_continuous(trans='log10')
```

